custom: [
  "http://donate.spikespaz.com",
  "https://www.buymeacoff.ee/spikespaz",
  "https://www.microsoft.com/store/productId/9P8ZJJ80RZ2K"
]
github: [spikespaz]
ko_fi: spikespaz
open_collective: spikespaz
